# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbac < Formula
  desc "A CLI tool for managing multiple databases, users, and permissions"
  homepage "https://github.com/bestcloudforme/dbac"
  version "0.0.7"
  license "GPL-3.0"

  on_macos do
    url "https://github.com/bestcloudforme/dbac/releases/download/v0.0.7/dbac_0.0.7_darwin_amd64.tar.gz"
    sha256 "d3cf6ec44da296d2fa779e594d8218920446f782a97e555859665efa175a8054"

    def install
      bin.install "dbac"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Dbac
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bestcloudforme/dbac/releases/download/v0.0.7/dbac_0.0.7_linux_amd64.tar.gz"
        sha256 "e9d2cae3a67f29cd50f245a05c22ddcfbeaab34310604232517aa0d8b5f5e3cb"

        def install
          bin.install "dbac"
        end
      end
    end
  end
end
