# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbac < Formula
  desc "A CLI tool for managing multiple databases, users, and permissions"
  homepage "https://github.com/bestcloudforme/dbac"
  version "0.0.2"
  license "GPL-3.0"

  on_macos do
    url "https://github.com/bestcloudforme/dbac/releases/download/v0.0.2/dbac_0.0.2_darwin_amd64.tar.gz"
    sha256 "453524e547f14f4a756db90247ae9effaac5e02164d0bb946d7a2f6d945cdc87"

    def install
      bin.install "dbac"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Dbac
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bestcloudforme/dbac/releases/download/v0.0.2/dbac_0.0.2_linux_amd64.tar.gz"
        sha256 "4c815101ff5d62ab1f69e6f187b3af45f55c485f83c7cad9372dedc6dfc23310"

        def install
          bin.install "dbac"
        end
      end
    end
  end
end
