# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbac < Formula
  desc "A CLI tool for managing multiple databases, users, and permissions"
  homepage "https://github.com/bestcloudforme/dbac"
  version "0.0.9"
  license "GPL-3.0"

  on_macos do
    url "https://github.com/bestcloudforme/dbac/releases/download/v0.0.9/dbac_0.0.9_darwin_amd64.tar.gz"
    sha256 "5f849b4f232a8ed563d92ccedb4f4e3b185a8ff98ad8e255c791359a8ef4b30c"

    def install
      bin.install "dbac"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Dbac
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bestcloudforme/dbac/releases/download/v0.0.9/dbac_0.0.9_linux_amd64.tar.gz"
        sha256 "83878c9d1f9ac976051f0ce945a4e3f28cc0987bec856416b071dead3dccb6bc"

        def install
          bin.install "dbac"
        end
      end
    end
  end
end
